# Generated by Django 3.2.6 on 2021-09-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intership', '0002_rename_last_date_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='stipend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
